<a href="https://colab.research.google.com/github/Hatsuhinode/ML-Algorithm/blob/main/Linear_Regression_Gradient_Descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Regression using gradient descent

*Gradient Descent* is an optimization algorithm for finding optimal solutions to wide range of problems. The idea of Gradient Descent is to tweak parameters iteratively in order to minimize a cost function.

It measures the local gradient of the error function with regard to the parameter vector **θ** and it goes in the direction of descending gradient.

**Gradient** means an increase or decrease in the magnitude of a property. It simply means *slope*.

*Gradient Descent* measures the local gradient of the error function with regard to the parameter vector θ, and it goes in the direction of descending gradient. Once the gradient is zero, you have reached a minimum

You start by filling **θ** with random values (this is called random initialization). Then you improve it gradually, taking one baby step at a time, each step attempting to decrease the cost function (e.g., the MSE), until the algorithm converges to a minimum

An important parameter in Gradient Descent is the **size of the steps**, determined by the **learning rate** hyperparameter.

### Learning rate
* If learning rate is too high might make the algorithm diverge, with larger and larger values, failing to find a good solution.

* If the learning rate is too small, then the algorithm will have to go through many iterations to converge, which will take a long time.

### Point to consider

When using Gradient Descent, you should ensure that all features have a similar scale
(e.g., using Scikit-Learn’s *StandardScaler class)*, or else it will take much longer to converge.

*Gradient Descent* is a search in the model’s *parameter space*: the more parameters a model has, the more dimensions this space has, and the harder the search is.

# Batch Gradient Descent

In [ ]:
import numpy as np

In [ ]:
X=2 * np.random.rand(100,1)
y=4 + 3 * X + np.random.randn(100,1)

In [ ]:
# Adding x0=1 to each instance.
X_b=np.c_[np.ones((100,1)),X]

In [ ]:
# Initializing learing rate.
eta=0.1
n_iterations=1000
m=100

# Random initialization of parameter.
theta=np.random.randn(2,1)

for iterations in range(n_iterations):
  gradients=2/m*X_b.T.dot(X_b.dot(theta)-y)
  theta=theta-eta*gradients

In [ ]:
theta

array([[3.90690054],
       [3.03066399]])

m is the number of training instances and n is the number of features

# Stochastic Gradient Descent

Stochastic Gradient Descent picks a random instance in the training set at every step and computes the gradients based only on that single instance.

On the other hand, due to its stochastic (i.e., random) nature, this algorithm is much less regular than Batch Gradient Descent: instead of gently decreasing until it reaches the minimum, the cost function will bounce up and down, decreasing only on average. Over time it will end up very close to the minimum, but once it gets there it will continue to bounce around, never settling down. So once the algorithm stops, the final parameter values are good, but not optimal.


When the cost function is very irregular,this can actually help the algorithm jump out of local minima, so Stochastic Gradient Descent has a better chance of finding the global minimum than Batch Gradient Descent does.

Therefore, randomness is good to escape from local optima, but bad because it means that the algorithm can never settle at the minimum

One solution to this dilemma is to gradually reduce the learning rate. The steps start out large (which helps make quick progress and escape local minima), then get smaller and smaller, allowing the algorithm to settle at the global minimum.

The function that determines the learning rate at each iteration is called the *learning schedule*.

If the learning rate is reduced too quickly, you may get stuck in a local minimum, or even end up frozen halfway to the minimum. If the learning rate is reduced too slowly, you may jump around the minimum for a long time and end up with a suboptimal solution if you halt training too early.

In [ ]:
n_epochs=50
t0,t1=5,50 # Learning schedule hyperparameters.

In [ ]:
def learning_schedule(t):
  return t0/(t+t1)

In [ ]:
theta=np.random.randn(2,1) # Random initialization.

In [ ]:
for epochs in range(n_epochs):
  for i in range(m):
    random_index=np.random.randint(m)
    xi=X_b[random_index:random_index+1]
    yi=y[random_index:random_index+1]
    gradients=2 * xi.T.dot(xi.dot(theta)-yi)
    eta=learning_schedule(epochs * m +i)
    theta=theta- eta * gradients

In [ ]:
theta

array([[3.95394165],
       [2.96829998]])

When using Stochastic Gradient Descent, the training instances must be independent and identically distributed (IID) to ensure that the parameters get pulled toward the global optimum, on average. A simple way to ensure this is to shuffle the instances during training (e.g., pick each instance randomly, or shuffle the training set at the beginning of each epoch). If you do not shuffle the instances—for example, if the instances are sorted by label—then SGD will start by optimizing for one label, then the next, and so on, and it will not settle close to the global minimum.

In [ ]:
from sklearn.linear_model import SGDRegressor

In [ ]:
sgd_reg=SGDRegressor(max_iter=1000,tol=1e-3,penalty=None,eta0=0.1)
sgd_reg.fit(X,y.ravel())

SGDRegressor(eta0=0.1, penalty=None)

The *numpy.ravel()* functions returns contiguous flattened array(1D array with all the input-array elements and with the same type as it)

The above code doesnot use any regularization(penalty=None)

In [ ]:
sgd_reg.intercept_,sgd_reg.coef_

(array([3.82099108]), array([2.95560505]))

# Mini-batch Gradient Descent

At each step, instead of computing the gradients based on the full training set (as in Batch GD) or based on just one instance (as in Stochastic GD), Mini-batch GD computes the gradients on small random sets of instances called mini-batches.

The main advantage of Mini- batch GD over Stochastic GD is that you can get a performance boost from hardware optimization of matrix operations, especially when using GPUs.